/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Java2DRenderWindow.java
 *
 * Created on 23.08.2011, 13:53:23
 */

package de.d2dev.heroquest.engine.rendering.quads;

import de.d2dev.fourseasons.resource.ResourceLocator;

/**
 *
 * @author Sebastian Bordt
 */
public class Java2DRenderWindow extends javax.swing.JFrame {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Java2DRenderPanel renderPanel;

    /** Creates new form Java2DRenderWindow */
    public Java2DRenderWindow(QuadRenderModel m, ResourceLocator p) {
        initComponents();
        
        this.renderPanel = new Java2DRenderPanel(m, p);
        this.jScrollPane1.setViewportView( this.renderPanel );
    }
    
    public void setRenderModel(QuadRenderModel m) {
    	// change the model
    	this.renderPanel.setRenderModel( m );	
    
    	// repaint the whole window
    	this.repaint();
    }
    
    public Java2DRenderPanel getRenderPanel() {
    	return this.renderPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Java2D Render Window");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
